
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeRegistry from '@/components/theme/ThemeRegistry'
import Header from '@/layoutComponents/header/Header'
import Portada from '@/layoutComponents/header/Portada'
import "./globals.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body >
          <Header/>
          <Portada />
          {children}
        </body>
      </ThemeRegistry>
    </html>
  )
}
