
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeRegistry from '@/components/theme/ThemeRegistry'
import Header from '@/layoutComponents/header/Header'
import "./globals.css"
import FooterLayout from '@/layoutComponents/footer/FooterLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body >
          <Header />
          <main>
            {children}
          </main>
          <footer>
            <FooterLayout />
          </footer>
        </body>
      </ThemeRegistry>
    </html>
  )
}
